[build]
  # Build command for Next.js static export
  command = "npm run build"
  
  # Publish directory - where the built files are located
  publish = "out"
  
  # Node.js version (optional but recommended)
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Disable Next.js telemetry during build
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Ensure we're building for production
  NODE_ENV = "production"

# Handle client-side routing for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle 404 pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"