name: NPM build

on:
  push:
    branches: 
      - master
      - envoyx-qa
  pull_request:
    branches: 
      - master 
      - envoyx-qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install modules
        run: npm install
        working-directory: .

      - name: Build all packages
        run: npm run build
        working-directory: .
